In [1]:
import pandas as pd

df = pd.read_csv('data/spam.csv')
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
# Find duplicates
df.duplicated().any()

# Drop Duplicates
df.drop_duplicates(inplace=True)
df.duplicated().any()

np.False_

In [10]:
# Convert 'Text' column to lowercase
df['Message'] = df['Message'].str.lower()
df.head()

  Category                                            Message
0      ham  go until jurong point, crazy.. available only ...
1      ham                      ok lar... joking wif u oni...
2     spam  free entry in 2 a wkly comp to win fa cup fina...
3      ham  u dun say so early hor... u c already then say...
4      ham  nah i don't think he goes to usf, he lives aro...